import torch
import torch.nn.functional as F


def fgsm_attack(model, x, y, epsilon):
    x_adv = x.clone().detach().to(dtype=torch.float32).requires_grad_(True)

    logits = model(x_adv)
    loss = F.cross_entropy(logits, y)

    model.zero_grad()
    loss.backward()

    grad_sign = x_adv.grad.sign()
    x_adv = x_adv + epsilon * grad_sign
    x_adv = torch.clamp(x_adv, 0, 1)

    return x_adv.detach()


def bim_attack(model, x, y, epsilon, alpha, iters):
    x_adv = x.clone().detach()

    for _ in range(iters):
        x_adv.requires_grad_(True)

        logits = model(x_adv)
        loss = F.cross_entropy(logits, y)

        model.zero_grad()
        loss.backward()

        grad_sign = x_adv.grad.sign()
        x_adv = x_adv + alpha * grad_sign

        delta = torch.clamp(x_adv - x, min=-epsilon, max=epsilon)
        x_adv = torch.clamp(x + delta, 0, 1).detach()

    return x_adv


def pgd_attack(model, x, y, epsilon, alpha, iters, random_start=True):
    if random_start:
        delta = torch.empty_like(x).uniform_(-epsilon, epsilon)
        x_adv = torch.clamp(x + delta, 0, 1).detach()
    else:
        x_adv = x.clone().detach()

    for _ in range(iters):
        x_adv.requires_grad_(True)

        logits = model(x_adv)
        loss = F.cross_entropy(logits, y)

        model.zero_grad()
        loss.backward()

        grad_sign = x_adv.grad.sign()
        x_adv = x_adv + alpha * grad_sign

        delta = torch.clamp(x_adv - x, min=-epsilon, max=epsilon)
        x_adv = torch.clamp(x + delta, 0, 1).detach()

    return x_adv


def mean_ensemble_attack(model, x, y, epsilon, alpha, iters):
    """
    MEA = average of adversarial examples generated by FGSM, PGD, BIM
    """
    x_fgsm = fgsm_attack(model, x, y, epsilon)
    x_pgd = pgd_attack(model, x, y, epsilon, alpha, iters)
    x_bim = bim_attack(model, x, y, epsilon, alpha, iters)

    x_ens = (x_fgsm + x_pgd + x_bim) / 3.0
    x_ens = torch.clamp(x_ens, 0, 1)
    return x_ens.detach()


def weighted_ensemble_attack(model, x, y, epsilon, alpha, iters,
                            w_fgsm=0.4, w_pgd=0.3, w_bim=0.3):
    """
    WEA = weighted combination of adversarial examples
    """
    assert abs((w_fgsm + w_pgd + w_bim) - 1.0) < 1e-6

    x_fgsm = fgsm_attack(model, x, y, epsilon)
    x_pgd = pgd_attack(model, x, y, epsilon, alpha, iters)
    x_bim = bim_attack(model, x, y, epsilon, alpha, iters)

    x_ens = w_fgsm * x_fgsm + w_pgd * x_pgd + w_bim * x_bim
    x_ens = torch.clamp(x_ens, 0, 1)
    return x_ens.detach()
